<?php

/**
 * @file
 * Configuration for `samlauth` integration with Enterprise Authentication.
 */

$saml_auth_config = [
  "login_menu_item_title" => "Sign in with UT EID",
  "logout_menu_item_title" => "Sign out",
  "login_link_title" => "Sign in with UT EID",
  "login_auto_redirect" => FALSE,
  "login_redirect_url" => "",
  "logout_redirect_url" => "",
  "error_redirect_url" => "",
  "error_throw" => FALSE,
  "login_error_keep_session" => FALSE,
  "local_login_saml_error" => FALSE,
  "logout_different_user" => FALSE,
  "drupal_login_roles" => [],
  "sp_entity_id" => 'https://' . $_SERVER['HTTP_HOST'] . '/onelogin',
  "sp_name_id_format" => "urn:oasis:names:tc:SAML:2.0:nameid-format:transient",
  "sp_x509_certificate" => "file:sites/default/files/private/saml/assets/cert/sp-cert.crt",
  "sp_new_certificate" => "",
  "sp_private_key" => "file:sites/default/files/private/saml/assets/cert/sp-key.pem",
  "metadata_valid_secs" => "1",
  "metadata_cache_http" => FALSE,
  "idp_entity_id" => "https://enterprise.login.utexas.edu/idp/shibboleth",
  "idp_single_sign_on_service" => "https://enterprise.login.utexas.edu/idp/profile/SAML2/Redirect/SSO",
  "idp_single_log_out_service" => 'https://' . $_SERVER['HTTP_HOST'] . '/saml/sls',
  "idp_change_password_service" => "",
  "idp_certs" => "{  }",
  "idp_cert_encryption" => "",
  "unique_id_attribute" => "uid",
  "map_users" => FALSE,
  "map_users_name" => TRUE,
  "map_users_mail" => FALSE,
  "create_users" => FALSE,
  "sync_name" => FALSE,
  "sync_mail" => TRUE,
  "user_name_attribute" => "uid",
  "user_mail_attribute" => "mail",
  "request_set_name_id_policy" => FALSE,
  "strict" => FALSE,
  "security_metadata_sign" => FALSE,
  "security_authn_requests_sign" => FALSE,
  "security_logout_requests_sign" => FALSE,
  "security_logout_responses_sign" => FALSE,
  "security_nameid_encrypt" => FALSE,
  "security_signature_algorithm" => "",
  "security_encryption_algorithm" => "",
  "security_messages_sign" => FALSE,
  "security_assertions_signed" => TRUE,
  "security_assertions_encrypt" => TRUE,
  "security_nameid_encrypted" => FALSE,
  "security_want_name_id" => FALSE,
  "security_request_authn_context" => FALSE,
  "security_lowercase_url_encoding" => FALSE,
  "security_logout_reuse_sigs" => FALSE,
  "security_allow_repeat_attribute_name" => FALSE,
  "debug_display_error_details" => FALSE,
  "debug_log_in" => FALSE,
  "debug_log_saml_in" => FALSE,
  "debug_log_saml_out" => FALSE,
  "debug_phpsaml" => FALSE,
  "use_proxy_headers" => FALSE,
  "use_base_url" => TRUE,
  "bypass_relay_state_check" => FALSE,
];

foreach ($saml_auth_config as $key => $value) {
  $config['samlauth.authentication'][$key] = $value;
}
